version:                "3"
services:
  rstan:
    image: kosugitti/rstan-env:latest
    volumes:
      - ./:/home/rstudio
    ports:
      - 8787:8787
    environment:
      - PASSWORD=Lunar
    container_name: rstan_tbdx
