version:                "3"
services:
  rstan:
    image: kosugitti/rstan-env:latest
    volumes:
      - ./:/home/rstudio
    ports:
      - 8787:8787
    environment:
      - PASSWORD=Lunar
    container_name: rstan_tbdx

  pars:
    image: timewz667/sims-pars:latest
    volumes:
      - ./notebooks:/home/jovyan/work
      -
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=hi
    container_name: pars

